# Generated by Django 2.0.7 on 2018-07-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('body', models.TextField(verbose_name='body')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('tags', models.ManyToManyField(to='taxonomy.Tag')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
