# Generated by Django 2.0.7 on 2018-07-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('serial_number', models.CharField(max_length=8, verbose_name='serial number')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
    ]
