# Generated by Django 2.0.7 on 2018-07-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='etsy_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Etsy ID'),
        ),
    ]
