# Generated by Django 2.0.7 on 2018-08-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_auto_20180730_0546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-serial_number']},
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('coming_soon', 'Coming Soon'), ('for_sale', 'For Sale'), ('sold', 'Sold')], default='coming_soon', max_length=32),
        ),
    ]
